specVersion: 1.0.0
name: moonbeam-starter
version: 0.0.4
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for Moonbeam network
repository: "https://github.com/subquery/moonbeam-subql-starters"
schema:
  file: ./schema.graphql
network:
  chainId: "0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d"
  #  This endpoint might not be publicly available
  endpoint: "wss://moonbeam.api.onfinality.io/public-ws"
  dictionary: "https://api.subquery.network/sq/subquery/moonbeam-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
