version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node-evm:
    image: subquerynetwork/subql-node-ethereum:latest
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --multi-chain
      - --db-schema=multi-chain
      - --disable-historical
      - -f=app/evm.yaml
      - --batch-size=30
      - --workers=4
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://subquery-node-ethereum:3000/ready
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-substrate:
    image: subquerynetwork/subql-node-substrate:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=app/substrate.yaml
      - --multi-chain
      - --db-schema=multi-chain
      - --disable-historical
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://subquery-node-project-kusama:3000/ready
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=multi-chain
      - --playground
