specVersion: 0.2.0
name: quartz-subql-starter
version: 0.0.4
description: This project can be use as a starting point for quartz network.
repository: https://github.com/subquery/quartz-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://quartz.api.onfinality.io/public-ws
  genesisHash: '0xcd4d732201ebe5d6b014edda071c4203e16867305332301dc8d092044b28e554'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/subquery/quartz-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
