specVersion: 1.0.0
name: bitcountry-starter
version: 0.0.5
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This SubQuery project can be use as a starting point for Bitcountry-pioneer
  network
repository: 'https://github.com/subquery/bitcountry-pioneer-subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0xf22b7850cdd5a7657bbfd90ac86441275bbc57ace3d2698a740c7b0ec4de5ec3'
  endpoint: 'wss://pioneer.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/bitcountry-pioneer-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
