name: PR
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: setup workspace
        run: cp .github/scripts/ci.package.json package.json
      # Do this before yarn to avoid node_modules directory
      - name: update tsconfigs for workspace
        run: ./.github/scripts/copy-ts-config.sh
      - run: yarn
      - name: codegen
        run: yarn codegen
      - name: build
        run: yarn build
